spring.application.name=kintai_spring
# message 
spring.messages.basename=i18n/messages,i18n/ValidationMessages

###############
#
# DB設定
#
###############
# DB接続先
spring.datasource.url=jdbc:mysql://localhost:3306/kintai_spring
# DBユーザ
spring.datasource.username=root
# DBパスワード
spring.datasource.password=
# ドライバ
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# アプリケーション起動時にDBを初期化する
spring.sql.init.mode=always
###############
#
# MyBatis設定
#
###############
# 文字ケースを変換する（テーブルカラム名：スネークケース<-> Javaのマッピング：キャメルケース）
mybatis.configuration.map-underscore-to-camel-case=true
# MapperXMLのパス
mybatis.mapper-locations=classpath*:mapper/mysql/*.xml
# MapperXMLに含めるモデルパッケージ名
mybatis.type-aliases-package=com.example.demo.domain.model
###############
#
# ログ設定
#
###############
# 開発中はログレベルをdebugモードにする
logging.level.com.example.demo=debug